
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovlmyyoezfpcisjwfopl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bG15eW9lemZwY2lzandmb3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTE4MTksImV4cCI6MjA2MTMyNzgxOX0.L2GNibJENsS5URyg2NQcN2hmv9IxaBowN5FWCWPT6Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
